apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: r7
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://48FB7DC549B0C21D10E272E9DC4858CB.gr7.us-east-1.eks.amazonaws.com
    namespace: default
  project: default
  source:
    helm:
      releaseName: v1
      valueFiles:
        - other-values.yaml
    path: charts/foo
    repoURL: https://github.com/kzw/foobar
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
