apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: r5
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: charts/foo
    repoURL: https://github.com/kzw/foobar
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

