apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  labels:
    app: foo
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: public.ecr.aws/docker/library/bash
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo {{ .Values.message }} $(date -u) >> /tmp/out.txt; sleep 5; done"]
